# Generated by Django 5.1 on 2025-02-07 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=30, unique=True)),
                ('course_name', models.CharField(default=' ', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=30)),
                ('register_id', models.CharField(max_length=30, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('parent', models.CharField(max_length=30)),
                ('parent_no', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('full_day_attendance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('mobile', models.CharField(default='mobile', max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('semester-1', 'Semester 1'), ('semester-2', 'Semester 2'), ('semester-3', 'Semester 3'), ('semester-4', 'Semester 4'), ('semester-5', 'Semester 5'), ('semester-6', 'Semester 6')], default='semester-1', max_length=20)),
                ('subject_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradeWireapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('exam_name', models.CharField(max_length=50)),
                ('internalMarks', models.PositiveIntegerField(default=0)),
                ('externalMarks', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradeWireapp.course')),
                ('registerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradeWireapp.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradeWireapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField(choices=[(1, 'Hour 1'), (2, 'Hour 2'), (3, 'Hour 3'), (4, 'Hour 4'), (5, 'Hour 5')])),
                ('is_present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='GradeWireapp.student')),
            ],
            options={
                'unique_together': {('student', 'date', 'hour')},
            },
        ),
    ]
