# Generated by Django 5.1 on 2025-01-22 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeWireapp', '0010_rename_name_course_course_id_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_day_attendance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField(choices=[(1, 'Hour 1'), (2, 'Hour 2'), (3, 'Hour 3'), (4, 'Hour 4'), (5, 'Hour 5')])),
                ('is_present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='GradeWireapp.student')),
            ],
            options={
                'unique_together': {('student', 'date', 'hour')},
            },
        ),
    ]
