# Generated by Django 5.1 on 2025-01-29 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeWireapp', '0011_student_full_day_attendance_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('exam_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('internal_marks', models.IntegerField()),
                ('external_marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradeWireapp.student')),
            ],
        ),
    ]
