# Generated by Django 5.1 on 2025-01-29 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeWireapp', '0012_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='student',
            new_name='registerId',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='external_marks',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='internal_marks',
        ),
        migrations.AddField(
            model_name='marks',
            name='externalMarks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='internalMarks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradeWireapp.course'),
        ),
    ]
